apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:G4y3OXJvHz45neklLHn7h95qj2Ewuu3SnGr5gXhie84xp2sTbsmC/g==,iv:6ux/HP8Wj+JHbd2rBVgGTC8DoMzOTgu32ZfkBtDt5wc=,tag:rW0Wbrj7LYJXXnkTVET+Tg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VHhVNmwxcS92V1Q3MXh4
            VngzTTBRZUJoVjVIbm0xNXZMSEJLUFVhUWkwCkEyQkNueDRlU2FjQ0lGTlg4RDRu
            NUpTOUFFcmJUWGxLODlOR2hHWnEzSk0KLS0tIFVZVk9jMElPTzRJWWZFSUg1bEtS
            QkgxOXNmbmN0N0czNVB4UWN2TVN1clEK3zzl9DwZoV9FZFzaBCNQgDAVcmzC7vPZ
            GVSNpMgB5aJ+0S0ON25i0wTdg0alUR5ufKNAilcpUyfqu9EVW8viaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T17:50:44Z"
    mac: ENC[AES256_GCM,data:m81EO/is1Kb/vatmE/NsyPktLlNnGOkrzhxpsLjHT2MY2RDLyP0O3QHbWVWB+aRqnV3YgX+gB3SnteIhetvfDh+eGWxJaP1ktuqAq7IGsanQ0cQVH2Jl0Uz2cnjVHO7WesUv9NygLdPcHsL3QkUELsHSg0jDmG6yawIcX1SM09E=,iv:jKpTCFBJ6znlZS4c3zBgZhHJY0vd4Ye4Z8VkUWloRnw=,tag:jXa3N7xQczoUZCtgsOJAAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
