apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/WzbaEnT9db/+OanZ3FVzbDCOb8COTFvsvN9eP27vCtoBJYfv3OfYw==,iv:Pz3/TiZKdJe9YBwaWuZfzx/7gIU3y9Vkwz4FY8G5r7A=,tag:7vJQcwzIasJrQ8Mjd0k3Gw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaXlJNXpYTW9HL1Rram1Q
            eTdtaEhWQmF4cGJraEhhd1c2cHMzUjlSZlRFCmVLamZ2ejFmTXdMVUFDVWlrS1BB
            K203YkNMbVRBQ1RFcXJ5WmIwckNPcWMKLS0tIDh3SENIeEpmZ1F4TFlTWUhWSW9Z
            RkFXZjgydTJSRTh2YnBDUkhKUUdKWWMKBNiYVwqr2OlI4Ko2+82VO/1AeKu7Zzch
            AFatNVnx01k7F9H9pRSqYf/JuA6Dco1JJiBm2TD6U3NsH5Xcu1mL1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T12:09:36Z"
    mac: ENC[AES256_GCM,data:VAmT/HCSAstZjxnIGZUe/QKtgBNzlDFzVGMmWWwR+PclJOjI1QYBVWLOKPe9wDmouq86pyxDYg5HvW4YPrvWg0Omd0tsJsg3DA8n+9WECrshmYzj63vxaIkgCvJKfP5DLhJWTZPdQATLnfXvkju3d1PhaQq2ttuB2xyoS+89KGo=,iv:40nN99WlUHlMK2MhPtm/yv5VXs00N0dsg3ghzY+5tww=,tag:ptVvcVJ0WaqXVzqI6wmrNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
