apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Uq/Ba8+LGD1Nhnn19ppuECWZtEmTYPxVveBkbf1xrJGVFjXC2kE6Gw==,iv:iYuZZ3GVba5PSk/348oVQ+9RlULw2tM/sDULBfHFb1g=,tag:XBd7Rnp812yvNvn1CxK9vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbmxSMkN1V1V1ZHEyWWZK
            djJIRXMxWXRHTWZLTzNGcUx5QjVVaXRuT1FBCjRRSkNoY0ozNnpiclZiTjZZdEk3
            SWVhdTM4K1NyZWRHb0pmeUlFaUxseUEKLS0tIENNQksvZXNHVkxDd1hXVUYyeWZM
            VGNwODdLb05jWEl5ekNDbk5PV2hSdzgKSDr8AQEV0R79p3rOehaueT7Cv6iL1ORR
            126v4LNx6hAwzTKPR25l+dw7N62OTXsZhzh1n7g5y9xUNC+Dr0QeEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-05T08:16:50Z"
    mac: ENC[AES256_GCM,data:+hDgVCUGNTJZcqoKb+JHZX0jOqVtPIApF1dlNBbLwfhHbcob2JFr2vwFaU++zKsCm7kuo0RC+bQwcn/NnSHIfjWXjL55DUZyn6sJco5H/AYmyt7LmFjSVl3VAhHSzjKHJ02wP6t0c53gVRsp6qFOT8AeyQHMQaG8OuJmtLFgKyk=,iv:7YzapGppwmeBKLQ8gbSxi/AMzjF6/g8vPlX8J2UvOXU=,tag:zzz/89n+qANTsjBsUM3hgA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
