apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ehivQzk0Jrz22ejuXIG6zG+b0T98lJz09re9BtIW/Yf/59mmZahKgsWpPT+Eq4daIvAeIeWG9QMgRNJdTWr3pDZQWwOZWi4cPr5OmXBsfgn+CdeXPeqp1x+UO3/LEavAsoUQwfad3ttko0ZmCXReq0j63jLCP4zRIFrFStX1TK94qdtCFyCIG34wCuf/w5vBwPgFWfy61tMake/PhiYoJTVrsTXhD53TNhsmjyBhxRkk0AXmw55leN42sI4kvwVpkuk6BDkUKcY8BHDQbfVjdsmX8y2+Um8LKhDq9uqCuCd22zpHx2VRrkqxtfB0fTxIApqk2H4S+0CVge2nJ86qLn4mbJL75tNMqYuaIE1VVAhW+Jh25XVDODyEO41Iv6Sl,iv:gOM59tn6ydg8FZpp8xOjTIvbkhZRNvTMNqWwDB5dfPo=,tag:MFFDUFG+A+mJtNeGHNRyjg==,type:str]
    identity.pub: ENC[AES256_GCM,data:/tg/B01vVNUYB4CYM+iusPh3XdIxDsFTi09YQlVvTsb0ARN3M6G9bmu8GkkTusOgygZ7YbbixgfUozKvBW7e6Gv4GkIPpDbicjTBZC9pjI3kBRIIC7jQVgcTpTfLWcOwVYk0VtAzcM0Eg/Wih/TbZK7Zug6OrG1u+eylXlND0cjQ2/SH+eKLLpQ3pdWxuQGVtISYUmZ5BlbKRBVOOJUPVdqeHn6INvYo/PqLb0wVjcHKNOId+8wmSftCBHMItA+2nFGilkHwxaKYeL+VLQ==,iv:W7iWo04I/QmzbT3fd2+/m4jd/+DE2TrXT5KdByFV2So=,tag:z2omOtvYvril/gp/6n6Nww==,type:str]
    known_hosts: ENC[AES256_GCM,data:Oud15ZJaf0lmt7WvzwhvNVF17GxvHLvKE2Qpcb8bChtoF9RkaviV/vPgpQbzOMRwSLmpDdPTubHSwlzFqf6EuVU3xgglSROJ0DUrsj0BbVPqWEER69hJlByXZz+p/VYU8dFeG+TE73cgbeYOnZ7pMUIchqYUQY0kWzTZugr2pBB6jGhaOBPG0QwmniUgqBazWl0oET2ia/m8H+G6yjA+8u5/UXPe9xIwP1qU,iv:OJmXYUK1qYhGaLejVYkqdRC5i7EkS1MsWgZJ1Ac9Hmo=,tag:x7ppAbyxaxfemuzgdhosAA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc3drbDF6QUFrZmRpYTV3
            bmp6anhiYm1xcXVXbDZHZGUyQmtpL0hLMjJjCjI3N3dhR3huQkNSUEhxWmZCS3I0
            Y0FyZ1NaNkhSNHh1aWZVWm5rSW5NbkUKLS0tIGw4SWw5QzBpT2dScEtkSnord1l0
            L0xBa01MS1hxdkdkWnQ2Q0JHam9LWWsKth9UnngBA0/7vULTiKo/q5PQWMQbZ2yg
            wG/7BC5v4lMSoDv8atGZ0JDTgOGOCZB2xTvrrK+Zu1xX63KFSP+SmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-22T08:38:47Z"
    mac: ENC[AES256_GCM,data:SAyVYl2XQF0OPesaVzSAWxfWJbPebQU7FicdkWuYgFklpzGYkRnW9WbTzP61xHzmfjRqh4l6CblJbdIH7XfNayfKY/XpIJHOtegZwt+RPr8NwL7v0EL+syPBlUX4yiXUcgyHbs8MMOyHXQtEYdQ6NF7VDEpEj0sjiwPi8FvXPXE=,iv:00yopUUOZr7ERVK7G4pqkX6kfZcqwO3NxKXxNo/aSHM=,tag:J1oKpRHZrQiVVJUJzmp+IQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
