apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bwFXV9vKVo8gyjzQnfEULgobSY7llLsvYpSp54E6tzuA9fDj0saFm+N3q5c3q9XfKf4SoN6XQeXVfdCSzXg/aF0gAZDp8JYXIQkrAEMZXN/VgrZjE96ADXyGPuieFH3yqki2wawrl0NQhf8ITT4F0inaAwf+8htG7hvC8FWKsba3ei3FlpSzlQIxDbQyZTCGZMEzaOu+XLkWhBFYgh43HNcIyVRlGpWlUQYqxS3V+qRoi6S3X4fghyVFDXmSkymNCKY7ff36zSTAbqoIWhavoKCgVFSa/tC6igkzCWiSPd3HKC85oOvRpP6ujmPO3W0CXlA0dMdFeYeClk5xpXmvC/B4zaQUUTSfAMoISOuQG02WGjfMwEE1ppakk686ESAb,iv:WwuWnYi/8rNwcVJNWBoDOshWc93XcrG9i2WcBXcGoSU=,tag:kstZoxC/sDLcl2XQOeTkHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:t74gzxjwI+JS7Djy3ntYwB54FDS3ur+CW592mSCpAB3Uc22uoh3Fr780BPXGXMPeRTUQoiOnxv5/PmqCb06WyHWM4cAO8gGifD96t4uEqv/8qrmx81a/nR7XB2hS8o1oGsvoIvW5P344AyU+9XQrNKXY8Lty/e3PMCrqZ8P/5ewwMbbUChl1b523UJ1XUabtvlcTFz1cfUPqQDzpgFS0OcYbQInPQ1h/3nFEuq0kGN+DhTxhqpcCvjP74oAxO/a2WKTZmjDMJubs3g2LLw==,iv:j+OqX97QmAUQ3xgKPnmlHppFiRE9IPwfFPfEl+ldU4w=,tag:0B76S2MrVPRsgsDjgkpnMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:n1NHYI0GrK6wAIQyonIGJ7a+anmEz2kSBvLRm6Rcge6jmpkdOZ5bTmgaAbgpDCrmQ/maFzNSqW5sQt5oKIH20WtjYX++QXeAFXJ64NHTt8DS0OWdr/3YxYTtxngQlle+rWKA69osfz2qJW0WHwepYiTezp+CV+5AqQMO+/skLmcxGLJupOWU4do/9r8XA1U01G4ipW/EOVDmQxzej6ODn8DtYCVvIMpd/LkQ,iv:D7/YPAem02SIDDfTnkvZamHrlARN+3W7hut/SsZyFPk=,tag:SQX32ZpWY18smh0rcsCaFA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRTM2SSt6eThyemNtMXJ0
            eHArd0VqdXFTSFlTdVJJVHpHMjgyb0NPcW1ZCjIyS3VmckRYQVFTUmtLa2QvOThO
            aTlxNG1VTzF0aGVCM0lUZVp0ckNBQ1kKLS0tIE5abVkzY21qU2Zka2xSVWRuNWRZ
            d0dENDNhaTFOdGJmai9JejArcGZkSjAKC4AF6lPI5TXmIpyeTsP8GBW+Rm+YrDnI
            CHlkXaf5qUYVk1EdVPqKrE/atkJ+EwfXEZXyR8h+/x+dFQ6hU2nzfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-05T11:23:06Z"
    mac: ENC[AES256_GCM,data:mxDkBDi1QqSXCPRHRkj1cWNwKezWYWedIUNBNW0DDKWuqzU7OvC/6XsX9Q6y90KnlSoVck513oIoC+5sF8lh7lDx/pLkVd0a33mOxpZ6Tr67lsSjiItbeSfPc8UJWLCOYVfjj6brireyMxRfkjeqUTOfUW/9DKglgcWdnxvXbPI=,iv:XB/z7uPzhGJ3cA6N1D2W2ibfrV8nynNRj8GTZHQgb2E=,tag:WZnh/W0d6qYJPNHpoPTBIg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
