apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jcl3aW8g7wVRKn/EmX4optjD96I5rasbqFgbTuUzJ8MXZFoFniGyjDDrquTPwsaJMFk5/j5hPdBP52HK//4mCG4lXxhXXCM2KT+odTNj5ayfyiUhaLq9a/f7/LQ5FJHhPs7wghOgh7Xf+7zB3Y11N6IrpSfb69YoS4QXne+vCtwpnIkObzbwL6vDSeWYYGkEM+JdNgoY8/56ibLc2lMSUY4oD9BnhOoKwGoL4ZuSZspie0mumKLR4FIb7T0Fup8liBd025OiNBhFrG76h2oWtJOrRZDff4JZqIPPVZS+WUSPP9JR6goiMVkT6Mg/5PtgaVvqYjNBbV+uhwxMzTaOFLZMzaF8WRVdHco3r/zfVNLaXNJTJGblitNWkKLDqcPi,iv:2ft9tCiyb+hRTaHpMj42Dp4wh0S/E3jDIH8YjjmxC48=,tag:1eNKn2zAIOfqUjYEC5sofQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JyOsd2OZslR9nrYP2xpWSsESTMMuNeJK8+3xDzWa2tzXWRjuhoWd3/nMzvmBl7BRWQgzTD2ZZyU7xSdMATqzSHqgVCyCI8Om9MoQdm31jyoKCzr+kONxTo52nqEJqTXtDuY+ffVg7xLAbzDjzqv8vXRxQCOCKFXvBGkh1dpBz7G42UERKJ/3m+K7uh0izBGtkBxnHkVuDRIRgcCrWBevFfyeI2rz5sb0iKyKcPxtHIkbrpc5QHFnFKORBrWzMlT/JkxS0E/Gvl1nQZkysQ==,iv:+pRhcs2FhJCUrr8VoGQC5Yc5fqKu3kzSKRNvZldSdaM=,tag:e7ibI1gbMZ+uQCTHPo5M7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:FDcOSeBmkeHfdmejxWjl7CDsq7TTsvzXIMymzGQaRMLodAsx+qQzMW8JOhoBwjeeoe1az4pR40/5ocf/l9dSMoV/t5EGuzijWnpav+ZccNgk1UkMTeiZv0NDV1vuaa6L/7Yqs253oYVrMKpC5QjNB0qYvTFvr5hylKwI4FOoy1izeMdKis7GI6ounLs1VQLyUuCOPs0SF7J9iaUalIudj0PnwEpzemEJ9LR9,iv:p/xdSJihONZ2gpcyoa1GQXtQa7NMhzabalZp0N59SF0=,tag:bDJ7oul4mMtL6KKMfZwjvw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RFF4M2JQY3RYVU5BUCs1
            Yjh5eFRDb3ovclkwSTJEeW1vc3JCamtYcEJjCjdOOGljYzZQRENxWjlGbFFlZVFS
            Y3MvUjNaWU1rYnQweVJSNHhZUDhsS0EKLS0tIGZUM3dWTzNwZksrRmpRajdwc25k
            bFFpMVd0MGJXSzlBaEg3S3p0Y2pWWDQKtV4WRZpfVkVecBJIKgtG8MrocfQYFVi1
            KOmp/GKdomGBCI9FxY+arlmDi+TSl8ixR3bPsSsaW/5YjAz7W/JFaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T17:10:32Z"
    mac: ENC[AES256_GCM,data:gAWfV/jtAj6iix5bJGZwDzKKWrdEwqAkfAjQCoz2eV+s2ReWHUcHZn7/A7Vx3Cf5bV1U60Y+hoXBBmBr3/OoKsYc4787ojwD5qn2btOQ40t61excKr7aM8xOjkzRc2nI7HupzvxCrA3AmJbjyI76JHQpmP4vvARYIkv+U5caVVc=,iv:duuzCL7eekL7O1UHANdhN1lROCKIQ1Iz0fzFPrsjOZ4=,tag:0qRE+CrGMyRYbNTnbRDhVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
